repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2  # Use the latest version tag from https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        args: ["--fix"]  # Optional: Auto-fix issues
      - id: ruff-format  # Enable Ruff's formatter
